import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Pages</h1>
      <main className={`${styles.main} ${inter.className}`}>
        <ul>
          <li>
            <Link href="/main">main</Link>
          </li>
          <li>
            <Link href="/some-page">some page</Link>
          </li>
          <li>
            <Link href="/missing-page">missing page</Link>
          </li>
          <li>
            <Link href="/page-deprecated">page deprecated</Link>
          </li>
        </ul>
      </main>
    </>
  );
}
